# Multi-stage build

# Stage 1: Install Anaconda
FROM base_lab_image:v1.1 as installer

ARG USERNAME
ARG PASSWD
ARG UID
ARG GID

# Create user with specified UID and GID
RUN groupadd -g ${GID} ${USERNAME} && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} ${USERNAME} && \
    usermod -aG sudo ${USERNAME} && \
    echo "${USERNAME}:${PASSWD}" | chpasswd

# Set working directory
WORKDIR /tmp/install

# Copy anaconda installation script
COPY Anaconda3-2023.09-0-Linux-x86_64.sh /tmp/install/anaconda3.sh

# Install Anaconda
RUN mkdir -p /home/${USERNAME}/softwares
RUN chmod +x /tmp/install/anaconda3.sh && \
    ./anaconda3.sh -b -p /home/${USERNAME}/softwares/anaconda3

# Stage 2: Build the final image
FROM base_lab_image:v1.1

LABEL maintainer="Huangwei <huangwei21b@ict.ac.cn>"

ARG USERNAME
ARG PASSWD
ARG UID
ARG GID

# Create user with specified UID and GID
RUN groupadd -g ${GID} ${USERNAME} && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} ${USERNAME} && \
    usermod -aG sudo ${USERNAME} && \
    echo "${USERNAME}:${PASSWD}" | chpasswd

RUN echo "${USERNAME} ALL=(ALL) ALL" > /etc/sudoers.d/${USERNAME} && chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}:${USERNAME}

# Copy Anaconda installation directory
RUN mkdir -p /home/${USERNAME}/softwares
COPY --from=installer /home/${USERNAME}/softwares/anaconda3 /home/${USERNAME}/softwares/anaconda3

# Set working directory
WORKDIR /home/${USERNAME}/workspace

VOLUME /home/${USERNAME}/workspace

# Configure Conda and Pip
ENV PATH /home/${USERNAME}/softwares/anaconda3/bin:$PATH
RUN /home/${USERNAME}/softwares/anaconda3/bin/conda init bash && \
    /home/${USERNAME}/softwares/anaconda3/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && \
    /home/${USERNAME}/softwares/anaconda3/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ && \
    /home/${USERNAME}/softwares/anaconda3/bin/conda config --set show_channel_urls yes && \
    /home/${USERNAME}/softwares/anaconda3/bin/pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# Initialize conda in shell, create conda environment, activate conda environment and install packages
RUN . /home/${USERNAME}/softwares/anaconda3/etc/profile.d/conda.sh && \
    conda create -n tevatron python=3.10 -y && \
    conda activate tevatron && \
    conda install -y faiss-gpu=1.7.4 mkl=2021 pytorch pytorch-cuda numpy -c pytorch -c nvidia && \
    python -m pip install transformers tokenizers tensorboard tensorboardx boto3 regex tqdm

EXPOSE 22

ENTRYPOINT ["/usr/bin/env"]

CMD echo ${PASSWD} | sudo -S service ssh start && /bin/bash
